<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductAndStockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Smartphone Category
            [
                'outlet_id' => 54,
                'category_id' => 15,
                'supplier_id' => 20,
                'product_name' => 'iPhone 14 Pro Max',
                'product_code' => 'IP14PM-256',
                'description' => 'iPhone 14 Pro Max 256GB - Midnight',
                'price_modal' => 15000000,
                'price_grosir' => 15500000,
                'price' => 16000000,
                'brand' => 'Apple',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 15,
                'supplier_id' => 20,
                'product_name' => 'Samsung Galaxy S23 Ultra',
                'product_code' => 'SGS23U-256',
                'description' => 'Samsung Galaxy S23 Ultra 256GB - Phantom Black',
                'price_modal' => 14000000,
                'price_grosir' => 14500000,
                'price' => 15000000,
                'brand' => 'Samsung',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Laptop Category
            [
                'outlet_id' => 54,
                'category_id' => 16,
                'supplier_id' => 21,
                'product_name' => 'MacBook Pro M2',
                'product_code' => 'MBP-M2-512',
                'description' => 'MacBook Pro M2 512GB - Space Gray',
                'price_modal' => 18000000,
                'price_grosir' => 18500000,
                'price' => 19000000,
                'brand' => 'Apple',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 16,
                'supplier_id' => 21,
                'product_name' => 'ROG Zephyrus G14',
                'product_code' => 'ROG-G14-3060',
                'description' => 'ASUS ROG Zephyrus G14 RTX 3060 1TB SSD',
                'price_modal' => 16000000,
                'price_grosir' => 16500000,
                'price' => 17000000,
                'brand' => 'ASUS',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Aksesoris Komputer
            [
                'outlet_id' => 54,
                'category_id' => 17,
                'supplier_id' => 22,
                'product_name' => 'Logitech MX Master 3S',
                'product_code' => 'LOG-MX3S',
                'description' => 'Logitech MX Master 3S Wireless Mouse',
                'price_modal' => 1200000,
                'price_grosir' => 1300000,
                'price' => 1400000,
                'brand' => 'Logitech',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 17,
                'supplier_id' => 22,
                'product_name' => 'Keychron K3',
                'product_code' => 'KEY-K3-RGB',
                'description' => 'Keychron K3 RGB Mechanical Keyboard',
                'price_modal' => 1000000,
                'price_grosir' => 1100000,
                'price' => 1200000,
                'brand' => 'Keychron',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Printer & Scanner
            [
                'outlet_id' => 54,
                'category_id' => 18,
                'supplier_id' => 23,
                'product_name' => 'Epson L3210',
                'product_code' => 'EPS-L3210',
                'description' => 'Epson EcoTank L3210 All-in-One Printer',
                'price_modal' => 2000000,
                'price_grosir' => 2100000,
                'price' => 2200000,
                'brand' => 'Epson',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Gaming
            [
                'outlet_id' => 54,
                'category_id' => 19,
                'supplier_id' => 24,
                'product_name' => 'PS5 Digital Edition',
                'product_code' => 'PS5-DE',
                'description' => 'PlayStation 5 Digital Edition',
                'price_modal' => 7000000,
                'price_grosir' => 7200000,
                'price' => 7500000,
                'brand' => 'Sony',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Networking
            [
                'outlet_id' => 54,
                'category_id' => 20,
                'supplier_id' => 25,
                'product_name' => 'TP-Link Archer AX73',
                'product_code' => 'TPL-AX73',
                'description' => 'TP-Link Archer AX73 AX5400 Wi-Fi 6 Router',
                'price_modal' => 1500000,
                'price_grosir' => 1600000,
                'price' => 1700000,
                'brand' => 'TP-Link',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Smart Home
            [
                'outlet_id' => 54,
                'category_id' => 21,
                'supplier_id' => 26,
                'product_name' => 'Google Nest Hub',
                'product_code' => 'GGL-NEST2',
                'description' => 'Google Nest Hub (2nd Generation)',
                'price_modal' => 1300000,
                'price_grosir' => 1400000,
                'price' => 1500000,
                'brand' => 'Google',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Audio & Speaker
            [
                'outlet_id' => 54,
                'category_id' => 22,
                'supplier_id' => 27,
                'product_name' => 'Sony WH-1000XM5',
                'product_code' => 'SNY-WH5',
                'description' => 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
                'price_modal' => 4000000,
                'price_grosir' => 4200000,
                'price' => 4500000,
                'brand' => 'Sony',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kamera & CCTV
            [
                'outlet_id' => 54,
                'category_id' => 23,
                'supplier_id' => 28,
                'product_name' => 'Sony A7 IV',
                'product_code' => 'SNY-A7M4',
                'description' => 'Sony Alpha A7 IV Mirrorless Camera',
                'price_modal' => 28000000,
                'price_grosir' => 28500000,
                'price' => 29000000,
                'brand' => 'Sony',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Software & Lisensi
            [
                'outlet_id' => 54,
                'category_id' => 24,
                'supplier_id' => 29,
                'product_name' => 'Microsoft 365 Family',
                'product_code' => 'MS365-FAM',
                'description' => 'Microsoft 365 Family 1-year Subscription',
                'price_modal' => 1000000,
                'price_grosir' => 1100000,
                'price' => 1200000,
                'brand' => 'Microsoft',
                'unit' => 'License',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Additional Products
            [
                'outlet_id' => 54,
                'category_id' => 15,
                'supplier_id' => 20,
                'product_name' => 'Google Pixel 7 Pro',
                'product_code' => 'GP7P-256',
                'description' => 'Google Pixel 7 Pro 256GB - Obsidian',
                'price_modal' => 12000000,
                'price_grosir' => 12500000,
                'price' => 13000000,
                'brand' => 'Google',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 16,
                'supplier_id' => 21,
                'product_name' => 'Dell XPS 15',
                'product_code' => 'DELL-XPS15',
                'description' => 'Dell XPS 15 with RTX 3050Ti',
                'price_modal' => 20000000,
                'price_grosir' => 20500000,
                'price' => 21000000,
                'brand' => 'Dell',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 19,
                'supplier_id' => 24,
                'product_name' => 'Xbox Series X',
                'product_code' => 'XBOX-SX',
                'description' => 'Xbox Series X Gaming Console',
                'price_modal' => 7500000,
                'price_grosir' => 7700000,
                'price' => 8000000,
                'brand' => 'Microsoft',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 22,
                'supplier_id' => 27,
                'product_name' => 'Apple AirPods Pro',
                'product_code' => 'APP-PRON2',
                'description' => 'Apple AirPods Pro (2nd Generation)',
                'price_modal' => 3000000,
                'price_grosir' => 3200000,
                'price' => 3500000,
                'brand' => 'Apple',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 23,
                'supplier_id' => 28,
                'product_name' => 'Hikvision ColorVu',
                'product_code' => 'HIK-CV4MP',
                'description' => 'Hikvision ColorVu 4MP CCTV Camera',
                'price_modal' => 800000,
                'price_grosir' => 900000,
                'price' => 1000000,
                'brand' => 'Hikvision',
                'unit' => 'Unit',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'outlet_id' => 54,
                'category_id' => 24,
                'supplier_id' => 29,
                'product_name' => 'Adobe Creative Cloud',
                'product_code' => 'ACC-1Y',
                'description' => 'Adobe Creative Cloud 1-year Subscription',
                'price_modal' => 8000000,
                'price_grosir' => 8200000,
                'price' => 8500000,
                'brand' => 'Adobe',
                'unit' => 'License',
                'has_serial_number' => true,
                'user_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert products
        DB::table('products')->insert($products);

        // Now insert stock for each product
        $stocks = [];
        foreach ($products as $product) {
            $stocks[] = [
                'product_id' => DB::table('products')
                    ->where('product_code', $product['product_code'])
                    ->value('product_id'),
                'outlet_id' => 54,
                'stock' => rand(5, 20), // Random stock between 5 and 20
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        // Insert stocks
        DB::table('product_stock')->insert($stocks);
    }
}
